language: python
python:
  - 3.6.2
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install unittest2
env:
  - COVERAGE_FILE=".coverage"
services:
  - postgresql
before_script:
  - "psql -c 'create database flask_api;' -U postgres"
script:
  - nosetests --with-coverage --cover-package=tests
after_success:
  - coveralls